name: bookshelf

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build, test and start frontend
        run: |
          npm ci
          npm test
          npm start & npx wait-on http://localhost:3000
        working-directory: ./bookshelf/frontend-testing-library
        env:
          CI: true

      - name: Run acceptance tests
        uses: cypress-io/github-action@v2
        with:
          record: true
          working-directory: ./bookshelf/acceptance-testing
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Run component tests
        uses: cypress-io/github-action@v2
        with:
          record: true
          working-directory: ./bookshelf/frontend-cypress-component-testing
          install: false
          command: npm run test:cypress:ci
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
